export const TERMS_AND_CONDITIONS_TEXT = `
Políticas de Publicación Adlyceum
Adlyceum es una plataforma web privada que ofrece el servicio de publicación de tareas y proyectos de investigación a estudiantes universitarios, siempre bajo el consentimiento y supervisión de sus profesores. 
Las publicaciones, méritos académicos, apreciaciones de profesores y compañeros, así como demás información registrada en la plataforma por los usuarios, se guardan en el perfil de los estudiantes, quienes aceptan a partir de su suscripción y consentimiento a estos términos, que Adlyceum comparta dichos perfiles con empresas y organizaciones que ofrecen diversos beneficios a los estudiantes o a las unidades académicas donde estudian.
A continuación se detallan las condiciones de uso de la plataforma y condiciones sobre las publicaciones.
El criterio de publicación
Los profesores de cada curso y directores académicos, se reservan el derecho de publicación en Adlyceum, bajo la categoría del curso y unidad académica que les corresponde. En caso de criterios distintos entre el profesor tutor y el director, el juicio de este último siempre prevalecerá. El profesor tutor, actuará como evaluador de primera línea, como tal tiene el derecho de aprobar y rechazar publicaciones, en razón de su apreciación sobre el cumplimiento con los requerimientos del curso y los estándares de la unidad académica. 
Las publicaciones aprobadas por un profesor tutor, podrán ser retiradas de la plataforma y de los perfiles de los autores, aún después de publicadas, y sin previa notificación ni autorización de los autores, si el director académico así lo solicita. Adlyceum hará luego, las labores de notificación a los autores involucrados.
Si los autores consideran que no están siendo evaluados justamente por el profesor o el director académico, podrán escribir a info@adlyceum.com para solicitar una investigación. En casos especiales Adlyceum se reserva el derecho de publicar proyectos, bajo otra categoría distinta al curso y la unidad académica.
Finalmente Adlyceum se reserva el derecho de retirar publicaciones de la plataforma, y de los perfiles de los autores, si se demuestra que han sido generadas en forma fraudulenta o inapropiada, o por daño irremediable del texto y documentos adjuntos. Esto se hará con el debido reporte a los autores, y a la unidad académica para que esta tome, de considerarlo necesario, las medidas que correspondientes.
Derechos y responsabilidades de autoría
Los derechos, beneficios y responsabilidades derivadas del contenido de las publicaciones pertenecerán y se acreditarán siempre a los autores registrados al momento de publicación. Los autores registrados en las publicaciones, sólo pueden ser usuarios registrados en la plataforma Adlyceum, y por tanto estar de acuerdo con estos términos de uso.
Adlyceum preservará siempre visible en las publicaciones, el mérito de supervisión prestado por el profesor tutor.
No se admitirán cambios de autoría, una vez realizadas las publicaciones.
Derechos sobre las publicaciones
Adlyceum no cobrará a sus usuarios por las publicaciones realizadas.
Las autores ceden a Adlyceum el permiso para distribuir la publicación y a identificarla como la primera entidad que lo publicó.
Adlyceum podrá distribuir las publicaciones en  abierto a cualquier persona en la web, sólo a usuarios inscritos en Adlyceum, usuarios inscritos a una universidad o unidad académica específica, o usuarios en una categoría comercial específica. Los usuarios en las modalidades de distribución, son libres para leer, descargar, copiar, distribuir, imprimir, buscar, o hacer enlaces al texto completo de las publicaciones, siempre que esto se haga con el debido reconocimiento de los autores, y para fines no comerciales.
Adlyceum se compromete a colaborar, en la medida de sus capacidades, a defender el debido reconocimiento de las autorías y evitar reproducciones indebidas.
Adlyceum se compromete a mantener acceso libre a los autores a sus propias publicaciones y documentos, a través de la plataforma.
Adlyceum se compromete a preservar, en la medida de sus capacidades tecnológicas, la integridad del texto y los documentos adjuntos de las publicaciones. Pero podrá cambiar el diseño y formato de estos, según los estándares de publicación de la plataforma.
Adlyceum no se hará responsable por daños en las publicaciones o sus documentos adjuntos, ya sean estos por causa propia involuntaria, o causados por agentes externos. Pero se compromete a intentar contactar a los autores, a través de la propia plataforma y sus contactos disponibles, para coordinar cualquier restauración o reemplazo disponible de la publicación original.
Adlyceum podrá incrustar publicidad en las publicaciones, y beneficiarse de esta, en la medida que considere apropiada.
Adlyceum podrá ceder sus derechos sobre las publicaciones a una empresa sucesora del negocio, siempre y cuando mantenga las condiciones a los usuarios, dispuestas en estos términos.
Políticas de detección del plagio o mal uso de publicaciones
Adlyceum se compromete a desarrollar y/o implementar en la medida de sus capacidades, tecnologías para la detección de plagio y mal uso de publicaciones.
Adlyceum siempre será receptivo de denuncias de plagio, o mal uso de publicaciones, tanto de usuarios de la plataforma como por parte de autores o entidades externas.
Toda denuncia de plagio o mal uso de publicaciones será informada a los usuarios y unidades académicas involucradas, y sometido a una investigación interna de Adlyceum. De demostrarse que los usuarios de Adlyceum están siendo víctimas de plagio o mal uso de sus publicaciones, se colaborará con testimonio a favor de estos ante cualquier instancia académica, comercial o judicial que los autores quieran recurrir. Si se determina que la publicación en la plataforma Adlyceum ha sido elaborada inapropiadamente, la misma será eliminada, así como sus referencias en los perfiles de los usuarios involucrados. Este acto será comunicado a la unidad académica respectiva para que esté enterada y ejecute, si lo considera necesario, las medidas disciplinarias correspondientes.
`;